[server]
runOnSave = false  # Desactiva la detección automática de cambios para reducir el uso de inotify
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
